### ISSUE TITLE
Can I pass segue from passcode viewController?

### ISSUE THREAD

**Issue by chirayu25** [yankodimitrov/SwiftPasscodeLock#80]
Can I pass segue from passcode ViewController to another ViewController wherein I allow to select folders where user want to enable password and dissmis that ViewController on Save?

**Comment by chirayu25** [comment]
Can any one help me on this?

**Comment by chirayu25** [comment]
Awaiting for any help on this.

**Comment by jabwd** [comment]
No you cannot as SwiftPasscodeLock creates an entirely new window that it replaces the main window with. If you want to use segues you'll need to instantiate a custom PasscodelockviewController that does not involve this window creation. that is the root view controller or some other view controller in your UINavigationController stack.

**Comment by chirayu25** [comment]
@jabwd  Thanks for the response. Can you suggest any library for the same?

**Comment by jabwd** [comment]
@chirayu25 Like I said you can still use this library, though I'd recommend changing it's layout because it will get you rejected from the AppStore.

If you want to use SwiftPasscodeLock just don't use the presenter, but manually use the PasscodeLockViewController directly.

Keep in mind that SwiftPasscodeLock is not secure. It does not clear memory of the passcode.
